### ISSUE TITLE
Remove ParsePretty

### ISSUE THREAD

**Issue by santiweight** [santiweight/poker-base#21]
I'm not sure that ParsePretty is particularly useful for anything? I think Show/Read does a much better job. If people want to output/read from text, ParsePretty is probably not a good way.

**Comment by santiweight** [comment]
Also kills megaparsec dependency

**Comment by tonyday567** [comment]
Agreed. I like prettyprinter and the idea of a reverse parser for it is great but looks like a headache to maintain. Parsing is going to concentrate in hand histories, AFAIC See
