### ISSUE TITLE
License

### ISSUE THREAD

**Issue by santiweight** [santiweight/poker-base#36]
@tonyday567 

Do you know what a desirable license would be for this library. I've put nigh-zero thought in the license and just chose whatever seemed fine. I imagine you're more familiar with licenses and I'm happy to delegate to your wisdom.

**Comment by tonyday567** [comment]
I can see I haven't trashed my rep enough at this table: let's go!

I tend to go with whatever I randomly chose 10 years ago.

**Comment by tonyday567** [comment]
I had a look - good choice!
