### ISSUE TITLE
Pattern Synonyms for ShapedHole

### ISSUE THREAD

**Issue by santiweight** [santiweight/poker-base#47]
What do you think about the pattern synonyms for ShapedHole et al

I think we should kill them - although it sucks to access via the `Unsafe` constructors, the pattern synonyms are not particularly discoverable, and tools like Wingman will default to the unsafe constructors when pattern matching anyway.

@tonyday567

**Comment by tonyday567** [comment]
What about bidirectional, safe, Pattern Synonyms?

```
pattern Suited :: Rank -> Rank -> ShapedHole
pattern Suited r1 r2 <- UnsafeSuited r1 r2
  where
    Suited r1 r2 = fromMaybe (terror "wtf") (mkSuited r1 r2)
```

In one direction, pretty much the same as mkSuited, and so marginal I suppose, but it wraps up a safe constructor and the pattern match destructor in one api.

**Comment by santiweight** [comment]
Well my Haskell brain is immediately flinching at the error there...

**Comment by santiweight** [comment]
My instinct is that I don't like it because this is a safe API that can throw an error to the user.
